name: barcode_listener_example
description: Example project for Flutter barcode listener.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  visibility_detector: ^0.4.0+2
  flutter_barcode_listener: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
